# Generated by Django 4.1.7 on 2023-03-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_product_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunsetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
